project_id = "gveybpenbvfqqviyzylj"

[functions.extract-client-data]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.generate-backyard-image]
verify_jwt = false

[functions.estimate-backyard-price]
verify_jwt = false

[functions.send-design-email]
verify_jwt = false
